'''
    QuantLib with python example
    Copyright (C) 2014 John Orford

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''
from django.conf.urls import *

from volkills import views
from django.views.generic import TemplateView

urlpatterns = patterns('',

	#Equity option - calibrate
	url(r'^type/equity_option/style/(?P<style>american|european)/valuation/year/(?P<valuation_year>\d+)/month/(?P<valuation_month>\d+)/day/(?P<valuation_day>\d+)/strike_price/(?P<strike_price>\d+(?:\.\d+)?)/expiry/year/(?P<expiry_year>\d+)/month/(?P<expiry_month>\d+)/day/(?P<expiry_day>\d+)/put_or_call/(?P<put_or_call>call|put)/underlying_price/(?P<underlying_price>\d+(?:\.\d+)?)/market_value/(?P<market_value>\d+(?:\.\d+)?)/dividend_yield/(?P<dividend_yield>-?\d+(?:\.\d+)?)/interest_rate/(?P<interest_rate>\d+(?:\.\d+)?)/$', views.Equity_Option_Calibrate_Results.as_view(), name='Equity_Option_Calibrate_Results'),

	#Equity option - value
	url(r'^type/equity_option/style/(?P<style>american|european)/valuation/year/(?P<valuation_year>\d+)/month/(?P<valuation_month>\d+)/day/(?P<valuation_day>\d+)/strike_price/(?P<strike_price>\d+(?:\.\d+)?)/expiry/year/(?P<expiry_year>\d+)/month/(?P<expiry_month>\d+)/day/(?P<expiry_day>\d+)/put_or_call/(?P<put_or_call>call|put)/underlying_price/(?P<underlying_price>\d+(?:\.\d+)?)/volatility_rate/(?P<volatility_rate>\d+(?:\.\d+)?)/dividend_yield/(?P<dividend_yield>-?\d+(?:\.\d+)?)/interest_rate/(?P<interest_rate>\d+(?:\.\d+)?)/$', views.Equity_Option_Value_Results.as_view(), name='Equity_Option_Value_Results'),
	
	#Vanilla bond - calibrate
	url(r'^type/bond/valuation/year/(?P<valuation_year>\d+)/month/(?P<valuation_month>\d+)/day/(?P<valuation_day>\d+)/term_structure/1m/(?P<term_structure_1m>\d+(?:\.\d+)?)/3m/(?P<term_structure_3m>\d+(?:\.\d+)?)/6m/(?P<term_structure_6m>\d+(?:\.\d+)?)/1y/(?P<term_structure_1y>\d+(?:\.\d+)?)/2y/(?P<term_structure_2y>\d+(?:\.\d+)?)/3y/(?P<term_structure_3y>\d+(?:\.\d+)?)/5y/(?P<term_structure_5y>\d+(?:\.\d+)?)/7y/(?P<term_structure_7y>\d+(?:\.\d+)?)/10y/(?P<term_structure_10y>\d+(?:\.\d+)?)/20y/(?P<term_structure_20y>\d+(?:\.\d+)?)/30y/(?P<term_structure_30y>\d+(?:\.\d+)?)/face/(?P<face>\d+(?:\.\d+)?)/maturity/year/(?P<maturity_year>\d+)/month/(?P<maturity_month>\d+)/day/(?P<maturity_day>\d+)/market_value/(?P<market_value>\d+(?:\.\d+)?)/payment_frequency/(?P<payment_frequency>once|annual|semiannual|quarterly|bimonthly|monthly|weekly|daily)/coupon/(?P<coupon>\d+(?:\.\d+)?)$', views.Bond_Results_Calibrate.as_view(), name='Bond_Results_Calibrate'),
	
	#Vanilla bond - value
	url(r'^type/bond/valuation/year/(?P<valuation_year>\d+)/month/(?P<valuation_month>\d+)/day/(?P<valuation_day>\d+)/term_structure/1m/(?P<term_structure_1m>\d+(?:\.\d+)?)/3m/(?P<term_structure_3m>\d+(?:\.\d+)?)/6m/(?P<term_structure_6m>\d+(?:\.\d+)?)/1y/(?P<term_structure_1y>\d+(?:\.\d+)?)/2y/(?P<term_structure_2y>\d+(?:\.\d+)?)/3y/(?P<term_structure_3y>\d+(?:\.\d+)?)/5y/(?P<term_structure_5y>\d+(?:\.\d+)?)/7y/(?P<term_structure_7y>\d+(?:\.\d+)?)/10y/(?P<term_structure_10y>\d+(?:\.\d+)?)/20y/(?P<term_structure_20y>\d+(?:\.\d+)?)/30y/(?P<term_structure_30y>\d+(?:\.\d+)?)/face/(?P<face>\d+(?:\.\d+)?)/maturity/year/(?P<maturity_year>\d+)/month/(?P<maturity_month>\d+)/day/(?P<maturity_day>\d+)/spread/(?P<spread>\d+(?:\.\d+)?)/payment_frequency/(?P<payment_frequency>once|annual|semiannual|quarterly|bimonthly|monthly|weekly|daily)/coupon/(?P<coupon>\d+(?:\.\d+)?)$', views.Bond_Results_Value.as_view(), name='Bond_Results_Value'),
	
	#FRNs - value
	url(r'^type/frn/valuation/year/(?P<valuation_year>\d+)/month/(?P<valuation_month>\d+)/day/(?P<valuation_day>\d+)/term_structure/1m/(?P<term_structure_1m>\d+(?:\.\d+)?)/3m/(?P<term_structure_3m>\d+(?:\.\d+)?)/6m/(?P<term_structure_6m>\d+(?:\.\d+)?)/1y/(?P<term_structure_1y>\d+(?:\.\d+)?)/2y/(?P<term_structure_2y>\d+(?:\.\d+)?)/3y/(?P<term_structure_3y>\d+(?:\.\d+)?)/5y/(?P<term_structure_5y>\d+(?:\.\d+)?)/7y/(?P<term_structure_7y>\d+(?:\.\d+)?)/10y/(?P<term_structure_10y>\d+(?:\.\d+)?)/20y/(?P<term_structure_20y>\d+(?:\.\d+)?)/30y/(?P<term_structure_30y>\d+(?:\.\d+)?)/face/(?P<face>\d+(?:\.\d+)?)/maturity/year/(?P<maturity_year>\d+)/month/(?P<maturity_month>\d+)/day/(?P<maturity_day>\d+)/credit_spread/(?P<credit_spread>\d+(?:\.\d+)?)/payment_frequency/(?P<payment_frequency>once|annual|semiannual|quarterly|bimonthly|monthly|weekly|daily)/current_floating_rate/(?P<current_floating_rate>\d+(?:\.\d+)?)/spread/(?P<spread>\d+(?:\.\d+)?)/reference_index_term_structure/1m/(?P<reference_index_term_structure_1m>\d+(?:\.\d+)?)/3m/(?P<reference_index_term_structure_3m>\d+(?:\.\d+)?)/6m/(?P<reference_index_term_structure_6m>\d+(?:\.\d+)?)/1y/(?P<reference_index_term_structure_1y>\d+(?:\.\d+)?)/2y/(?P<reference_index_term_structure_2y>\d+(?:\.\d+)?)/3y/(?P<reference_index_term_structure_3y>\d+(?:\.\d+)?)/5y/(?P<reference_index_term_structure_5y>\d+(?:\.\d+)?)/7y/(?P<reference_index_term_structure_7y>\d+(?:\.\d+)?)/10y/(?P<reference_index_term_structure_10y>\d+(?:\.\d+)?)/20y/(?P<reference_index_term_structure_20y>\d+(?:\.\d+)?)/30y/(?P<reference_index_term_structure_30y>\d+(?:\.\d+)?)$', views.Frn_Results_Value.as_view(), name='Frn_Results_Value'),
	
	#FRNs - calibrate
	url(r'^type/frn/valuation/year/(?P<valuation_year>\d+)/month/(?P<valuation_month>\d+)/day/(?P<valuation_day>\d+)/term_structure/1m/(?P<term_structure_1m>\d+(?:\.\d+)?)/3m/(?P<term_structure_3m>\d+(?:\.\d+)?)/6m/(?P<term_structure_6m>\d+(?:\.\d+)?)/1y/(?P<term_structure_1y>\d+(?:\.\d+)?)/2y/(?P<term_structure_2y>\d+(?:\.\d+)?)/3y/(?P<term_structure_3y>\d+(?:\.\d+)?)/5y/(?P<term_structure_5y>\d+(?:\.\d+)?)/7y/(?P<term_structure_7y>\d+(?:\.\d+)?)/10y/(?P<term_structure_10y>\d+(?:\.\d+)?)/20y/(?P<term_structure_20y>\d+(?:\.\d+)?)/30y/(?P<term_structure_30y>\d+(?:\.\d+)?)/face/(?P<face>\d+(?:\.\d+)?)/maturity/year/(?P<maturity_year>\d+)/month/(?P<maturity_month>\d+)/day/(?P<maturity_day>\d+)/market_value/(?P<market_value>\d+(?:\.\d+)?)/payment_frequency/(?P<payment_frequency>once|annual|semiannual|quarterly|bimonthly|monthly|weekly|daily)/current_floating_rate/(?P<current_floating_rate>\d+(?:\.\d+)?)/spread/(?P<spread>\d+(?:\.\d+)?)/reference_index_term_structure/1m/(?P<reference_index_term_structure_1m>\d+(?:\.\d+)?)/3m/(?P<reference_index_term_structure_3m>\d+(?:\.\d+)?)/6m/(?P<reference_index_term_structure_6m>\d+(?:\.\d+)?)/1y/(?P<reference_index_term_structure_1y>\d+(?:\.\d+)?)/2y/(?P<reference_index_term_structure_2y>\d+(?:\.\d+)?)/3y/(?P<reference_index_term_structure_3y>\d+(?:\.\d+)?)/5y/(?P<reference_index_term_structure_5y>\d+(?:\.\d+)?)/7y/(?P<reference_index_term_structure_7y>\d+(?:\.\d+)?)/10y/(?P<reference_index_term_structure_10y>\d+(?:\.\d+)?)/20y/(?P<reference_index_term_structure_20y>\d+(?:\.\d+)?)/30y/(?P<reference_index_term_structure_30y>\d+(?:\.\d+)?)$', views.Frn_Results_Calibrate.as_view(), name='Frn_Results_Calibrate'),
	
	#Swaps - calibrate
	url(r'^type/swap/valuation/year/(?P<valuation_year>\d+)/month/(?P<valuation_month>\d+)/day/(?P<valuation_day>\d+)/term_structure/1m/(?P<term_structure_1m>\d+(?:\.\d+)?)/3m/(?P<term_structure_3m>\d+(?:\.\d+)?)/6m/(?P<term_structure_6m>\d+(?:\.\d+)?)/1y/(?P<term_structure_1y>\d+(?:\.\d+)?)/2y/(?P<term_structure_2y>\d+(?:\.\d+)?)/3y/(?P<term_structure_3y>\d+(?:\.\d+)?)/5y/(?P<term_structure_5y>\d+(?:\.\d+)?)/7y/(?P<term_structure_7y>\d+(?:\.\d+)?)/10y/(?P<term_structure_10y>\d+(?:\.\d+)?)/20y/(?P<term_structure_20y>\d+(?:\.\d+)?)/30y/(?P<term_structure_30y>\d+(?:\.\d+)?)/face/(?P<face>\d+(?:\.\d+)?)/maturity/year/(?P<maturity_year>\d+)/month/(?P<maturity_month>\d+)/day/(?P<maturity_day>\d+)/market_value/(?P<market_value>-?\d+(?:\.\d+)?)/start/year/(?P<start_year>\d+)/month/(?P<start_month>\d+)/day/(?P<start_day>\d+)/floating_leg_frequency/(?P<floating_leg_frequency>once|annual|semiannual|quarterly|bimonthly|monthly|weekly|daily)/fixed_leg_frequency/(?P<fixed_leg_frequency>once|annual|semiannual|quarterly|bimonthly|monthly|weekly|daily)/fixed_rate/(?P<fixed_rate>\d+(?:\.\d+)?)/spread/(?P<spread>\d+(?:\.\d+)?)/reference_index_term_structure/1m/(?P<reference_index_term_structure_1m>\d+(?:\.\d+)?)/3m/(?P<reference_index_term_structure_3m>\d+(?:\.\d+)?)/6m/(?P<reference_index_term_structure_6m>\d+(?:\.\d+)?)/1y/(?P<reference_index_term_structure_1y>\d+(?:\.\d+)?)/2y/(?P<reference_index_term_structure_2y>\d+(?:\.\d+)?)/3y/(?P<reference_index_term_structure_3y>\d+(?:\.\d+)?)/5y/(?P<reference_index_term_structure_5y>\d+(?:\.\d+)?)/7y/(?P<reference_index_term_structure_7y>\d+(?:\.\d+)?)/10y/(?P<reference_index_term_structure_10y>\d+(?:\.\d+)?)/20y/(?P<reference_index_term_structure_20y>\d+(?:\.\d+)?)/30y/(?P<reference_index_term_structure_30y>\d+(?:\.\d+)?)$', views.Irs_Results_Calibrate.as_view(), name='Irs_Results_Calibrate'),
	
	#Swaps - value
	url(r'^type/swap/valuation/year/(?P<valuation_year>\d+)/month/(?P<valuation_month>\d+)/day/(?P<valuation_day>\d+)/term_structure/1m/(?P<term_structure_1m>\d+(?:\.\d+)?)/3m/(?P<term_structure_3m>\d+(?:\.\d+)?)/6m/(?P<term_structure_6m>\d+(?:\.\d+)?)/1y/(?P<term_structure_1y>\d+(?:\.\d+)?)/2y/(?P<term_structure_2y>\d+(?:\.\d+)?)/3y/(?P<term_structure_3y>\d+(?:\.\d+)?)/5y/(?P<term_structure_5y>\d+(?:\.\d+)?)/7y/(?P<term_structure_7y>\d+(?:\.\d+)?)/10y/(?P<term_structure_10y>\d+(?:\.\d+)?)/20y/(?P<term_structure_20y>\d+(?:\.\d+)?)/30y/(?P<term_structure_30y>\d+(?:\.\d+)?)/face/(?P<face>\d+(?:\.\d+)?)/maturity/year/(?P<maturity_year>\d+)/month/(?P<maturity_month>\d+)/day/(?P<maturity_day>\d+)/credit_spread/(?P<credit_spread>-?\d+(?:\.\d+)?)/start/year/(?P<start_year>\d+)/month/(?P<start_month>\d+)/day/(?P<start_day>\d+)/floating_leg_frequency/(?P<floating_leg_frequency>once|annual|semiannual|quarterly|bimonthly|monthly|weekly|daily)/fixed_leg_frequency/(?P<fixed_leg_frequency>once|annual|semiannual|quarterly|bimonthly|monthly|weekly|daily)/fixed_rate/(?P<fixed_rate>\d+(?:\.\d+)?)/spread/(?P<spread>\d+(?:\.\d+)?)/reference_index_term_structure/1m/(?P<reference_index_term_structure_1m>\d+(?:\.\d+)?)/3m/(?P<reference_index_term_structure_3m>\d+(?:\.\d+)?)/6m/(?P<reference_index_term_structure_6m>\d+(?:\.\d+)?)/1y/(?P<reference_index_term_structure_1y>\d+(?:\.\d+)?)/2y/(?P<reference_index_term_structure_2y>\d+(?:\.\d+)?)/3y/(?P<reference_index_term_structure_3y>\d+(?:\.\d+)?)/5y/(?P<reference_index_term_structure_5y>\d+(?:\.\d+)?)/7y/(?P<reference_index_term_structure_7y>\d+(?:\.\d+)?)/10y/(?P<reference_index_term_structure_10y>\d+(?:\.\d+)?)/20y/(?P<reference_index_term_structure_20y>\d+(?:\.\d+)?)/30y/(?P<reference_index_term_structure_30y>\d+(?:\.\d+)?)$', views.Irs_Results_Value.as_view(), name='Irs_Results_Value'),

	#cds - calibrate
	url(r'^type/cds/valuation/year/(?P<valuation_year>\d+)/month/(?P<valuation_month>\d+)/day/(?P<valuation_day>\d+)/term_structure/1m/(?P<term_structure_1m>\d+(?:\.\d+)?)/3m/(?P<term_structure_3m>\d+(?:\.\d+)?)/6m/(?P<term_structure_6m>\d+(?:\.\d+)?)/1y/(?P<term_structure_1y>\d+(?:\.\d+)?)/2y/(?P<term_structure_2y>\d+(?:\.\d+)?)/3y/(?P<term_structure_3y>\d+(?:\.\d+)?)/5y/(?P<term_structure_5y>\d+(?:\.\d+)?)/7y/(?P<term_structure_7y>\d+(?:\.\d+)?)/10y/(?P<term_structure_10y>\d+(?:\.\d+)?)/20y/(?P<term_structure_20y>\d+(?:\.\d+)?)/30y/(?P<term_structure_30y>\d+(?:\.\d+)?)/nominal/(?P<nominal>-?\d+(?:\.\d+)?)/maturity/year/(?P<maturity_year>\d+)/month/(?P<maturity_month>\d+)/day/(?P<maturity_day>\d+)/market_value/(?P<market_value>-?\d+(?:\.\d+)?)/contract_spread/(?P<contract_spread>\d+(?:\.\d+)?)$', views.Cds_Results_Calibrate.as_view(), name='Cds_Results_Calibrate'),
	
	#cds - calibrate
	url(r'^type/cds/valuation/year/(?P<valuation_year>\d+)/month/(?P<valuation_month>\d+)/day/(?P<valuation_day>\d+)/term_structure/1m/(?P<term_structure_1m>\d+(?:\.\d+)?)/3m/(?P<term_structure_3m>\d+(?:\.\d+)?)/6m/(?P<term_structure_6m>\d+(?:\.\d+)?)/1y/(?P<term_structure_1y>\d+(?:\.\d+)?)/2y/(?P<term_structure_2y>\d+(?:\.\d+)?)/3y/(?P<term_structure_3y>\d+(?:\.\d+)?)/5y/(?P<term_structure_5y>\d+(?:\.\d+)?)/7y/(?P<term_structure_7y>\d+(?:\.\d+)?)/10y/(?P<term_structure_10y>\d+(?:\.\d+)?)/20y/(?P<term_structure_20y>\d+(?:\.\d+)?)/30y/(?P<term_structure_30y>\d+(?:\.\d+)?)/nominal/(?P<nominal>-?\d+(?:\.\d+)?)/maturity/year/(?P<maturity_year>\d+)/month/(?P<maturity_month>\d+)/day/(?P<maturity_day>\d+)/default_probability/(?P<default_probability>-?\d+(?:\.\d+)?)/contract_spread/(?P<contract_spread>\d+(?:\.\d+)?)$', views.Cds_Results_Value.as_view(), name='Cds_Results_Calibrate'),
	
	)